# Práctica 1: preprocesamiento de datos 101




### Introducción:
La metodología ```CRISP-DM``` es uno de los flujos de trabajo estándar seguido por los equipos de Data Science en todo el mundo. Nos concentraremos en las siguientes subsecciones de esta metodología: 

* Recolección de datos:  Comprender los diferentes mecanismos de recuperación de datos para los diferentes tipos de datos. 
* Descripción de los datos:  Comprender los diversos atributos y propiedades de los datos recopilados 
* Limpieza de datos:  Para preparar datos para el consumo en los pasos de modelación 
* Visualización de datos:  Visualizar diferentes atributos para compartir resultados, una mejor comprensión, etc. 

##### Cookbook [@data_mining_2020](https://nbviewer.jupyter.org/github/JacoboGGLeon/data_mining_2020/blob/master/README.ipynb)

## Resources

## Pandas 
### Python Data Analysis Library
* `pandas` is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.
* the name is derived from the term _panel data_, an econometrics term for **multidimensional structured data sets**.

[Official site](https://pandas.pydata.org/)

[A Quick Introduction to the “Pandas” Python Library](https://towardsdatascience.com/a-quick-introduction-to-the-pandas-python-library-f1b678f34673)
 
## NumPy
### Scientific Computing with Python
NumPy is the fundamental package for scientific computing with Python. It contains among other things:
* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities
* the name is short for Numerical Python

[Oficial site](http://www.numpy.org/)

[A Quick Introduction to the NumPy Library](https://towardsdatascience.com/a-quick-introduction-to-the-numpy-library-6f61b7dee4db)

## Matplotlib
### Plotting Library for Python
Matplotlib is a Python 2D plotting library which produces publication quality figures in a variety of hardcopy formats and interactive environments across platforms
* `matplotlib.pyplot` is a collection of command style functions that make matplotlib work like `MATLAB`.

[Oficial site](https://matplotlib.org/)

[Pyplot Tutorial](https://matplotlib.org/tutorials/introductory/pyplot.html)

## Recipe 

Import packages 

`import` package `as` alias

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Numpy ndarray
All of the numeric functionality of numpy is orchestrated by two important constituents of the numpy package, `ndarray` and `Ufuncs` (Universal function):
* Numpy `ndarray` is a multi-dimensional array object which is the core data container for all of the numpy operations. 
* `Universal functions` are the functions which operate on `ndarrays` in an element by element fashion. 

Arrays (or matrices) are one of the fundamental representations of data. Mostly an array will be of a single data type (homogeneous) and possibly multi-dimensional sometimes. 

In [0]:
array = np.array([1,3,4,5,6])
array

array([1, 3, 4, 5, 6])

In [0]:
type(array)

numpy.ndarray

The data type was picked up from the elements as they were all integers the data type is ```int32```

In [0]:
array.dtype

dtype('int64')

The ```shape``` attribute of the ```array``` object will tell us about the **dimensions** of the ```array```

In [0]:
array.shape

(5,)

An ```array``` of shape (3, ) is 1-dimensional and consists of 3 elements.

In [0]:
np.array([1,2,3]).shape

(3,)

An ```array``` of ```shape``` (3, 1) is 2-dimensional. It has 3 rows and 1 column.

In [0]:
np.array([[1],[2],[3]]).shape

(3, 1)

An ```array``` of ```shape``` (2, 3, 1) is 3-dimensional. It has 2 rows and 3 column 1 z

In [0]:
np.array([[[1],[2],[3]], [[1],[2],[3]]]).shape

(2, 3, 1)

**One important thing to keep in mind is that all the elements in an array must have the same data type.**

So a simple *rule of thumb* is dealing only with numeric data.

In [0]:
array = np.array([1,'st','er',3])
array.dtype

dtype('<U21')

In [0]:
np.sum(array)

TypeError: ignored

## Creating Arrays

In [0]:
array = np.array([[1,2,3],[2,4,6],[8,8,8]])
array

array([[1, 2, 3],
       [2, 4, 6],
       [8, 8, 8]])

In [0]:
array.shape

(3, 3)

### Numpy special functions

`np.zeros`: Creates a matrix of specified dimensions containing only zeroes

In [0]:
array = np.zeros((2,4))
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

`np.ones`: Creates a matrix of specified dimension containing only ones

In [0]:
array = np.ones((2,4))
array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

`np.identity`: Creates an identity matrix of specified dimensions

In [0]:
array = np.identity(3)
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

`randn`: Initialize an array of a specified dimension with random values (from the numpy.random)

In [0]:
array = np.random.randn(3,4)
array

array([[ 0.80915995, -0.24248622, -0.01813484, -1.58632906],
       [ 0.33467313, -0.72824391,  2.18303051,  2.02333712],
       [ 0.33950418,  0.23469447,  1.36787278, -1.0290849 ]])

### Accessing Array Elements

In [0]:
array = np.random.randn(3,4)
array[0]

array([-0.27703519,  0.72767088,  0.68898511,  0.02747083])

This access becomes interesting in the case of an array having more than two dimensions

In [0]:
array = np.arange(12).reshape(2,2,3)
array

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [0]:
array.shape

(2, 2, 3)

In [0]:
array[0]

array([[0, 1, 2],
       [3, 4, 5]])

Accessing arrays is the concept of slicing arrays

In [0]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
array.shape

(10,)

In [0]:
array[5:]

array([5, 6, 7, 8, 9])

In [0]:
array[:5]

array([0, 1, 2, 3, 4])

In [0]:
array[5:8]

array([5, 6, 7])

In [0]:
array[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [0]:
array[-2:]

array([8, 9])

If the number of dimensions in the object supplied is less than the dimension of the array being accessed then the colon (:) is assumed for all the dimensions.

In [0]:
array = np.arange(12).reshape(2,2,3)
array

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [0]:
array.shape

(2, 2, 3)

In [0]:
array[1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [0]:
array[1:2]

array([[[ 6,  7,  8],
        [ 9, 10, 11]]])

Another way to access an array is to use dots (...) based indexing

In [0]:
array = np.arange(27).reshape(3,3,3)
array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [0]:
array[:,:,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [0]:
array[...,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

### Operations on Arrays

* Universal functions are functions that operate on arrays in an element by element fashion. 
* The implementation of Ufunc is vectorized, which means that the execution of Ufuncs on arrays is quite fast.

In [0]:
array = np.arange(15).reshape(3,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
array + 5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
array * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [0]:
array_1 = np.arange(15).reshape(5,3)
array_1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [0]:
array_2 = np.arange(5).reshape(5,1)
array_2

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [0]:
array_1 + array_2

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

In [0]:
(array_1 + array_2).shape

(5, 3)

In [0]:
array_1 = np.random.randn(3,3)
array_1

array([[-1.34556578,  0.18882941, -0.54065947],
       [ 0.60879419, -0.35645769, -0.18230728],
       [-0.85076399,  1.39850277,  0.25400058]])

`modf` will return the fractional and the integer part of the input supplied to it

In [0]:
np.modf(array_1)

NameError: ignored

### Linear Algebra Using numpy

One of the most widely used operations in linear algebra is the dot product. 

This can be performed on two compatible (brush up on your matrices and array skills if you need to know which arrays are compatible for a dot product) ndarrays by using the dot function.

In [0]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
B = np.array([[9,8,7],[6,5,4],[1,2,3]])
B

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [0]:
A.dot(B)

array([[ 24,  24,  24],
       [ 72,  69,  66],
       [120, 114, 108]])

In [0]:
B.dot(A)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 30,  36,  42]])

In [0]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
B = np.array([[9,8,7],[6,5,4]])
B

array([[9, 8, 7],
       [6, 5, 4]])

In [0]:
A.dot(B)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [0]:
A = np.arange(15).reshape(3,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
A.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#### Data Retrieval
* Pandas provides numerous ways to retrieve and read in data. 
* We can convert data from CSV files, databases, flat files, and so on into dataframes. 
* We can also convert a list of dictionaries (Python dict) into a dataframe. 

#### List of Dictionaries to Dataframe
This is one of the simplest methods to create a dataframe.

In [0]:
d =  [{'city':'Guadalajara',"population":1000},
      {'city':'CDMX',"population":2000},
      {'city':'Monterrey',"population":1000}]
d

[{'city': 'Guadalajara', 'population': 1000},
 {'city': 'CDMX', 'population': 2000},
 {'city': 'Monterrey', 'population': 1000}]

In [0]:
type({'city':'Guadalajara',"population":1000})

dict

In [0]:
type(d)

list

In [0]:
pd.DataFrame(d)

city  population
0  Guadalajara        1000
1         CDMX        2000
2    Monterrey        1000

In [0]:
df = pd.DataFrame(d)
df

city  population
0  Guadalajara        1000
1         CDMX        2000
2    Monterrey        1000

### Data Access

#### Head and Tail

In [0]:
# https://datos.gob.mx/busca/dataset/numero-de-jornales-pagados
path = '/Users/jacoboleon/Downloads/Empleo_Temporal_Jornales.csv'
#df = pd.read_csv(filepath_or_buffer=path)
df = pd.read_csv(filepath_or_buffer=path, encoding='latin')
df

Clave del Estado Nombre del Estado  Clave del Municipio  \
0                    1    AGUASCALIENTES                    1   
1                    1    AGUASCALIENTES                    1   
2                    1    AGUASCALIENTES                    1   
3                    1    AGUASCALIENTES                    1   
4                    1    AGUASCALIENTES                    1   
5                    1    AGUASCALIENTES                    1   
6                    1    AGUASCALIENTES                    1   
7                    1    AGUASCALIENTES                    1   
8                    1    AGUASCALIENTES                    1   
9                    1    AGUASCALIENTES                    1   
10                   1    AGUASCALIENTES                    1   
11                   1    AGUASCALIENTES                    1   
12                   1    AGUASCALIENTES                    1   
13                   1    AGUASCALIENTES                    1   
14                   1    AGUASCALIENTES                    1   
15                   1    AGUASCALIENTES                    1   
16                   1    AGUASCALIENTES                    1   
17                   1    AGUASCALIENTES                    1   
18                   1    AGUASCALIENTES                    1   
19                   1    AGUASCALIENTES                    1   
20                   1    AGUASCALIENTES                    1   
21                   1    AGUASCALIENTES                    1   
22                   1    AGUASCALIENTES                    1   
23                   1    AGUASCALIENTES                    1   
24                   1    AGUASCALIENTES                    1   
25                   1    AGUASCALIENTES                    1   
26                   1    AGUASCALIENTES                    1   
27                   1    AGUASCALIENTES                    1   
28                   1    AGUASCALIENTES                    1   
29                   1    AGUASCALIENTES                    1   
...                ...               ...                  ...   
4723                32         ZACATECAS                   38   
4724                32         ZACATECAS                   38   
4725                32         ZACATECAS                   38   
4726                32         ZACATECAS                   38   
4727                32         ZACATECAS                   38   
4728                32         ZACATECAS                   38   
4729                32         ZACATECAS                   38   
4730                32         ZACATECAS                   38   
4731                32         ZACATECAS                   38   
4732                32         ZACATECAS                   38   
4733                32         ZACATECAS                   38   
4734                32         ZACATECAS                   38   
4735                32         ZACATECAS                   38   
4736                32         ZACATECAS                   38   
4737                32         ZACATECAS                   38   
4738                32         ZACATECAS                   38   
4739                32         ZACATECAS                   38   
4740                32         ZACATECAS                   38   
4741                32         ZACATECAS                   38   
4742                32         ZACATECAS                   38   
4743                32         ZACATECAS                   38   
4744                32         ZACATECAS                   38   
4745                32         ZACATECAS                   38   
4746                32         ZACATECAS                   38   
4747                32         ZACATECAS                   38   
4748                32         ZACATECAS                   38   
4749                32         ZACATECAS                   38   
4750                32         ZACATECAS                   38   
4751                32         ZACATECAS                   38   
4752                32         ZACATECAS 

In [0]:
type(df)

pandas.core.frame.DataFrame

In [0]:
df.head()

Clave del Estado Nombre del Estado  Clave del Municipio  \
0                 1    AGUASCALIENTES                    1   
1                 1    AGUASCALIENTES                    1   
2                 1    AGUASCALIENTES                    1   
3                 1    AGUASCALIENTES                    1   
4                 1    AGUASCALIENTES                    1   

  Nombre del Municipio  Clave de la Localidad  \
0       AGUASCALIENTES                      1   
1       AGUASCALIENTES                    120   
2       AGUASCALIENTES                    121   
3       AGUASCALIENTES                    126   
4       AGUASCALIENTES                    127   

             Nombre de la Localidad  Número de Jornales  
0                    AGUASCALIENTES              118220  
1            BUENAVISTA DE PEÑUELAS                2000  
2  CABECITA 3 MARÍAS (RANCHO NUEVO)                 660  
3             ESTACIÓN CAÑADA HONDA                 560  
4                         LOS CAÑOS                3900

In [0]:
df.tail()

Clave del Estado Nombre del Estado  Clave del Municipio  \
4748                32         ZACATECAS                   38   
4749                32         ZACATECAS                   38   
4750                32         ZACATECAS                   38   
4751                32         ZACATECAS                   38   
4752                32         ZACATECAS                   56   

     Nombre del Municipio  Clave de la Localidad  \
4748                PINOS                    520   
4749                PINOS                    532   
4750                PINOS                    534   
4751                PINOS                    572   
4752            ZACATECAS                      1   

                        Nombre de la Localidad  Número de Jornales  
4748  JESÚS MARÍA SUR (SAN ANTONIO DE LA CRUZ)                 200  
4749                                LOMA LINDA                 600  
4750                        ESQUINA DE DOLORES                 260  
4751  SANTA FE DEL POLVO (VEINTE DE NOVIEMBRE)                 360  
4752                                 ZACATECAS               15000

In [0]:
df.columns = ['cve_est', 'nom_est', 'cve_mun', 'nom_mun', 'cve_loc', 'nom_loc', 'num_jor']
df.tail()

cve_est    nom_est  cve_mun    nom_mun  cve_loc  \
4748       32  ZACATECAS       38      PINOS      520   
4749       32  ZACATECAS       38      PINOS      532   
4750       32  ZACATECAS       38      PINOS      534   
4751       32  ZACATECAS       38      PINOS      572   
4752       32  ZACATECAS       56  ZACATECAS        1   

                                       nom_loc  num_jor  
4748  JESÚS MARÍA SUR (SAN ANTONIO DE LA CRUZ)      200  
4749                                LOMA LINDA      600  
4750                        ESQUINA DE DOLORES      260  
4751  SANTA FE DEL POLVO (VEINTE DE NOVIEMBRE)      360  
4752                                 ZACATECAS    15000

#### Slicing and Dicing

In [0]:
serie = df['Clave del Estado']
type(serie)

pandas.core.series.Series

In [0]:
serie.shape

(4753,)

In [0]:
len(serie)

4753

In [0]:
#serie[:round(len(serie)/120)]
serie[:5]

0    1
1    1
2    1
3    1
4    1
Name: Clave del Estado, dtype: int64

In [0]:
df[:10]

cve_est         nom_est  cve_mun         nom_mun  cve_loc  \
0        1  AGUASCALIENTES        1  AGUASCALIENTES        1   
1        1  AGUASCALIENTES        1  AGUASCALIENTES      120   
2        1  AGUASCALIENTES        1  AGUASCALIENTES      121   
3        1  AGUASCALIENTES        1  AGUASCALIENTES      126   
4        1  AGUASCALIENTES        1  AGUASCALIENTES      127   
5        1  AGUASCALIENTES        1  AGUASCALIENTES      135   
6        1  AGUASCALIENTES        1  AGUASCALIENTES      138   
7        1  AGUASCALIENTES        1  AGUASCALIENTES      139   
8        1  AGUASCALIENTES        1  AGUASCALIENTES      144   
9        1  AGUASCALIENTES        1  AGUASCALIENTES      171   

                             nom_loc  num_jor  
0                     AGUASCALIENTES   118220  
1             BUENAVISTA DE PEÑUELAS     2000  
2   CABECITA 3 MARÍAS (RANCHO NUEVO)      660  
3              ESTACIÓN CAÑADA HONDA      560  
4                          LOS CAÑOS     3900  
5  EL CEDAZO (CEDAZO DE SAN ANTONIO)      600  
6        CENTRO DE ARRIBA (EL TARAY)     3000  
7          CIENEGUILLA (LA LUMBRERA)     2880  
8           EL COLORADO (EL SOYATAL)     1000  
9     LOS CUERVOS (LOS OJOS DE AGUA)     1260

For providing access to **specific rows** and **specific columns**, pandas provides useful functions like `iloc` and `loc` which can be used to refer to specific rows and columns in a dataframe. 

This allows us to select the rows and columns using structure similar to array slicing. 

In [0]:
df.iloc[:5,:4]

cve_est         nom_est  cve_mun         nom_mun
0        1  AGUASCALIENTES        1  AGUASCALIENTES
1        1  AGUASCALIENTES        1  AGUASCALIENTES
2        1  AGUASCALIENTES        1  AGUASCALIENTES
3        1  AGUASCALIENTES        1  AGUASCALIENTES
4        1  AGUASCALIENTES        1  AGUASCALIENTES

In [0]:
df[df['num_jor'] > 200000]

cve_est  nom_est  cve_mun              nom_mun  cve_loc  \
749         7  CHIAPAS      101     TUXTLA GUTIÉRREZ        1   
1374       15   MEXICO       33  ECATEPEC DE MORELOS        1   
1444       15   MEXICO      104  TLALNEPANTLA DE BAZ        1   
2526       20   OAXACA       67     OAXACA DE JUÁREZ        1   

                  nom_loc  num_jor  
749      TUXTLA GUTIÉRREZ   709874  
1374  ECATEPEC DE MORELOS   654224  
1444         TLALNEPANTLA   298155  
2526     OAXACA DE JUÁREZ   259232

In [0]:
df[(df['num_jor'] > 200000) & (df['cve_est'] == 15)]

cve_est nom_est  cve_mun              nom_mun  cve_loc  \
1374       15  MEXICO       33  ECATEPEC DE MORELOS        1   
1444       15  MEXICO      104  TLALNEPANTLA DE BAZ        1   

                  nom_loc  num_jor  
1374  ECATEPEC DE MORELOS   654224  
1444         TLALNEPANTLA   298155

#### Data Operations

In [0]:
df = pd.DataFrame(np.random.randn(8, 3), columns=['A', 'B', 'C'])
df

A         B         C
0 -1.347760 -0.582922 -1.216476
1 -1.098666  0.091047 -0.478008
2  1.166976 -0.006884 -1.023639
3 -0.103616 -0.333166  0.216110
4  0.776747 -1.133099 -1.101388
5 -1.126257  0.328468 -0.616320
6 -1.570903 -1.421313 -0.423321
7  2.320741  1.371522  0.024430

Values Attribute

In [0]:
nparray = df.values
nparray

array([[-1.34775974, -0.58292179, -1.21647554],
       [-1.09866555,  0.09104712, -0.47800792],
       [ 1.16697631, -0.00688426, -1.02363895],
       [-0.10361551, -0.33316641,  0.21610958],
       [ 0.77674738, -1.13309882, -1.10138813],
       [-1.12625735,  0.32846815, -0.61631968],
       [-1.57090319, -1.42131325, -0.42332106],
       [ 2.32074125,  1.37152194,  0.02443045]])

In [0]:
type(nparray)

numpy.ndarray

Missing Data and the fillna Function

In [0]:
df.iloc[4,2] = np.NaN
df

A         B         C
0 -1.347760 -0.582922 -1.216476
1 -1.098666  0.091047 -0.478008
2  1.166976 -0.006884 -1.023639
3 -0.103616 -0.333166  0.216110
4  0.776747 -1.133099       NaN
5 -1.126257  0.328468 -0.616320
6 -1.570903 -1.421313 -0.423321
7  2.320741  1.371522  0.024430

We have substituted the missing value with a default value. We can use a variety of methods to arrive at the substituting value (mean, median, and so on)

In [0]:
df.fillna(0)

A         B         C
0 -1.347760 -0.582922 -1.216476
1 -1.098666  0.091047 -0.478008
2  1.166976 -0.006884 -1.023639
3 -0.103616 -0.333166  0.216110
4  0.776747 -1.133099  0.000000
5 -1.126257  0.328468 -0.616320
6 -1.570903 -1.421313 -0.423321
7  2.320741  1.371522  0.024430

In [0]:
df.fillna(np.mean(df['C']))

A         B         C
0 -1.347760 -0.582922 -1.216476
1 -1.098666  0.091047 -0.478008
2  1.166976 -0.006884 -1.023639
3 -0.103616 -0.333166  0.216110
4  0.776747 -1.133099 -0.502460
5 -1.126257  0.328468 -0.616320
6 -1.570903 -1.421313 -0.423321
7  2.320741  1.371522  0.024430

Descriptive Statistics Functions

In [0]:
# https://datos.gob.mx/busca/dataset/numero-de-jornales-pagados
path = '/Users/jacoboleon/Downloads/Empleo_Temporal_Jornales.csv'
#df = pd.read_csv(filepath_or_buffer=path)
df = pd.read_csv(filepath_or_buffer=path, encoding='latin')
df.head(3)

Clave del Estado Nombre del Estado  Clave del Municipio  \
0                 1    AGUASCALIENTES                    1   
1                 1    AGUASCALIENTES                    1   
2                 1    AGUASCALIENTES                    1   

  Nombre del Municipio  Clave de la Localidad  \
0       AGUASCALIENTES                      1   
1       AGUASCALIENTES                    120   
2       AGUASCALIENTES                    121   

             Nombre de la Localidad  Número de Jornales  
0                    AGUASCALIENTES              118220  
1            BUENAVISTA DE PEÑUELAS                2000  
2  CABECITA 3 MARÍAS (RANCHO NUEVO)                 660

In [0]:
df.columns = ['cve_est', 'nom_est', 'cve_mun', 'nom_mun', 'cve_loc', 'nom_loc', 'num_jor']
df.tail(3)

cve_est    nom_est  cve_mun    nom_mun  cve_loc  \
4750       32  ZACATECAS       38      PINOS      534   
4751       32  ZACATECAS       38      PINOS      572   
4752       32  ZACATECAS       56  ZACATECAS        1   

                                       nom_loc  num_jor  
4750                        ESQUINA DE DOLORES      260  
4751  SANTA FE DEL POLVO (VEINTE DE NOVIEMBRE)      360  
4752                                 ZACATECAS    15000

Descriptive statistics of a dataframe give data scientists a comprehensive look into important information about any attributes and features in the dataset. 

In database management an aggregate function is a **function where the values of multiple rows are grouped together to form a single value** of more significant meaning or measurement such as a set, a bag or a list. 

* `count()`: function returns the number of rows that matches a specified criteria.
* `mean()`: function returns the average value of a numeric column.
* `sum()`: function returns the total sum of a numeric column.
* `median()`: function returns the median value in a set of values.

In [0]:
columns_numeric = ['cve_est','cve_mun','cve_loc', 'num_jor']

In [0]:
df[columns_numeric].mean()

cve_est      18.019987
cve_mun      70.186829
cve_loc     125.102041
num_jor    4478.785188
dtype: float64

In [0]:
df[columns_numeric].sum()

cve_est       85649
cve_mun      333598
cve_loc      594610
num_jor    21287666
dtype: int64

In [0]:
df[columns_numeric].count()

cve_est    4753
cve_mun    4753
cve_loc    4753
num_jor    4753
dtype: int64

In [0]:
df[columns_numeric].median()

cve_est      19.0
cve_mun      35.0
cve_loc      34.0
num_jor    1152.0
dtype: float64

In [0]:
df[columns_numeric].quantile(4/4)

cve_est        32.0
cve_mun       570.0
cve_loc      4718.0
num_jor    709874.0
Name: 1.0, dtype: float64

In [0]:
df[columns_numeric].sum(axis = 1)

0       118223
1         2122
2          783
3          688
4         4029
5          737
6         3140
7         3021
8         1146
9         1433
10        1472
11         793
12        1628
13        2059
14        1781
15        2438
16        1067
17        1887
18        1093
19        1295
20        1398
21        3097
22        5339
23        1331
24        1212
25        1024
26        1791
27        1439
28        1846
29        1463
         ...  
4723       989
4724       813
4725       737
4726       741
4727      1323
4728       550
4729       911
4730       562
4731      1264
4732      1035
4733      1079
4734       786
4735       749
4736       690
4737       463
4738      1109
4739      1381
4740       494
4741       709
4742       665
4743       694
4744       710
4745      1266
4746       784
4747       815
4748       790
4749      1202
4750       864
4751      1002
4752     15089
Length: 4753, dtype: int64

In [0]:
df[columns_numeric].describe()

cve_est      cve_mun      cve_loc        num_jor
count  4753.000000  4753.000000  4753.000000    4753.000000
mean     18.019987    70.186829   125.102041    4478.785188
std       7.842396   102.391741   284.169262   18713.914438
min       1.000000     1.000000     1.000000       0.000000
25%      12.000000    11.000000     7.000000     500.000000
50%      19.000000    35.000000    34.000000    1152.000000
75%      25.000000    85.000000   115.000000    3480.000000
max      32.000000   570.000000  4718.000000  709874.000000

### Concatenating Dataframes

In [0]:
df_sample_01 = df.sample(3)
df_sample_01

cve_est     nom_est  cve_mun      nom_mun  cve_loc  \
1846       16   MICHOACAN       66    PÁTZCUARO       61   
2337       19  NUEVO LEON       17      GALEANA       61   
4273       29    TLAXCALA       10  CHIAUTEMPAN        1   

                    nom_loc  num_jor  
1846    JOYA DE LOS MOLINOS      500  
2337                NAVIDAD      576  
4273  SANTA ANA CHIAUTEMPAN     2970

In [0]:
df_sample_02 = df.sample(3)
df_sample_02

cve_est     nom_est  cve_mun    nom_mun  cve_loc             nom_loc  \
4684       32   ZACATECAS       17  GUADALUPE       72    LAGUNA DE ARRIBA   
291         7     CHIAPAS        2      ACALA      412  SAN PEDRO PEDERNAL   
2356       19  NUEVO LEON       18     GARCIA        1              GARCÍA   

      num_jor  
4684      600  
291       460  
2356    34752

In [0]:
df_sample_03 = df.sample(3)
df_sample_03

cve_est    nom_est  cve_mun    nom_mun  cve_loc  \
1625       16  MICHOACAN       34    HIDALGO      122   
607         7    CHIAPAS       89  TAPACHULA      126   
1909       16  MICHOACAN       75  LOS REYES       13   

                      nom_loc  num_jor  
1625  SAN ANTONIO VILLALONGÍN      500  
607        JOSÉ MARÍA MORELOS     8960  
1909              PAMATÁCUARO     1500

In [0]:
df_combine = pd.concat([df_sample_01, df_sample_02, df_sample_03])
df_combine

cve_est     nom_est  cve_mun      nom_mun  cve_loc  \
1846       16   MICHOACAN       66    PÁTZCUARO       61   
2337       19  NUEVO LEON       17      GALEANA       61   
4273       29    TLAXCALA       10  CHIAUTEMPAN        1   
4684       32   ZACATECAS       17    GUADALUPE       72   
291         7     CHIAPAS        2        ACALA      412   
2356       19  NUEVO LEON       18       GARCIA        1   
1625       16   MICHOACAN       34      HIDALGO      122   
607         7     CHIAPAS       89    TAPACHULA      126   
1909       16   MICHOACAN       75    LOS REYES       13   

                      nom_loc  num_jor  
1846      JOYA DE LOS MOLINOS      500  
2337                  NAVIDAD      576  
4273    SANTA ANA CHIAUTEMPAN     2970  
4684         LAGUNA DE ARRIBA      600  
291        SAN PEDRO PEDERNAL      460  
2356                   GARCÍA    34752  
1625  SAN ANTONIO VILLALONGÍN      500  
607        JOSÉ MARÍA MORELOS     8960  
1909              PAMATÁCUARO     1500

Database Style Concatenations Using the merge Command

In [0]:
dict_A =  [{'city':'Monterrey',"population":np.random.randint(1, 10000)},
           {'city':'CDMX',"population":np.random.randint(1, 10000)},
           {'city':'Guadalajara',"population":np.random.randint(1, 10000)}]

A = pd.DataFrame(dict_A)
A

city  population
0    Monterrey        8542
1         CDMX        8032
2  Guadalajara        3449

In [0]:
dict_B =  [{'city':'Morelos',"population":np.random.randint(1, 10000)},
           {'city':'Veracruz',"population":np.random.randint(1, 10000)},
           {'city':'Baja California',"population":np.random.randint(1, 10000)}]

B = pd.DataFrame(dict_B)
B

city  population
0          Morelos        5976
1         Veracruz        9841
2  Baja California        8050

In [0]:
A.merge(right=B, left_on='city', right_on='city', how='outer')

city  population_x  population_y
0        Monterrey        8542.0           NaN
1             CDMX        8032.0           NaN
2      Guadalajara        3449.0           NaN
3          Morelos           NaN        5976.0
4         Veracruz           NaN        9841.0
5  Baja California           NaN        8050.0

In [0]:
A.merge(right=B, left_on='city', right_on='city', how='inner')

Empty DataFrame
Columns: [city, population_x, population_y]
Index: []

In [0]:
dict_A =  [{'city':'Guadalajara',"population":np.random.randint(1, 10000)},
           {'city':'CDMX',"population":np.random.randint(1, 10000)},
           {'city':'CDMX',"population":np.random.randint(1, 10000)},
           {'city':'Guadalajara',"population":np.random.randint(1, 10000)}]

A = pd.DataFrame(dict_A)
A

city  population
0  Guadalajara        3392
1         CDMX        4075
2         CDMX        4215
3  Guadalajara        8015

In [0]:
dict_B =  [{'city':'Veracruz', "population":np.random.randint(1, 10000)},
           {'city':'Morelos', "population":np.random.randint(1, 10000)},
           {'city':'CDMX', "population":np.random.randint(1, 10000)},
           {'city':'Tlaxcala', "population":np.random.randint(1, 10000)},
          {'city':'Chihuahua', "population":np.random.randint(1, 10000)},
          {'city':'Yucatán', "population":np.random.randint(1, 10000)}]

B = pd.DataFrame(dict_B)
B

city  population
0   Veracruz        2194
1    Morelos        3048
2       CDMX        1361
3   Tlaxcala        2576
4  Chihuahua        8354
5    Yucatán        5388

In [0]:
A.merge(right=B, left_on='city', right_on='city', how='outer')

city  population_x  population_y
0  Guadalajara        3392.0           NaN
1  Guadalajara        8015.0           NaN
2         CDMX        4075.0        1361.0
3         CDMX        4215.0        1361.0
4     Veracruz           NaN        2194.0
5      Morelos           NaN        3048.0
6     Tlaxcala           NaN        2576.0
7    Chihuahua           NaN        8354.0
8      Yucatán           NaN        5388.0

In [0]:
A.merge(right=B, left_on='city', right_on='city', how='inner')

city  population_x  population_y
0  CDMX          4075          1361
1  CDMX          4215          1361

In [0]:
dict_A =  [{'city':'Guadalajara',"population":np.random.randint(1, 10000)},
           {'city':'CDMX',"population":np.random.randint(1, 10000)},
           {'city':'CDMX',"population":np.random.randint(1, 10000)},
           {'city':'Guadalajara',"population":np.random.randint(1, 10000)}]

A = pd.DataFrame(dict_A)
A

city  population
0  Guadalajara        4467
1         CDMX        4881
2         CDMX        7666
3  Guadalajara        5931

In [0]:
dict_B =  [{'city':'Guadalajara', 'color': 'rojo', "population":np.random.randint(1, 10000)},
           {'city':'Morelos','color': 'azul', "population":np.random.randint(1, 10000)},
           {'city':'Monterrey','color': 'rojo', "population":np.random.randint(1, 10000)},
           {'city':'Tlaxcala', 'color': 'azul', "population":np.random.randint(1, 10000)},
          {'city':'Chihuahua', 'color': 'rojo', "population":np.random.randint(1, 10000)},
          {'city':'Yucatán', 'color': 'azul', "population":np.random.randint(1, 10000)}]

B = pd.DataFrame(dict_B)
B

city color  population
0  Guadalajara  rojo        8914
1      Morelos  azul         588
2    Monterrey  rojo         675
3     Tlaxcala  azul        3885
4    Chihuahua  rojo        3831
5      Yucatán  azul         339

In [0]:
A.merge(right=B, left_on='city', right_on='city', how='outer')

city  population_x color  population_y
0  Guadalajara        4467.0  rojo        8914.0
1  Guadalajara        5931.0  rojo        8914.0
2         CDMX        4881.0   NaN           NaN
3         CDMX        7666.0   NaN           NaN
4      Morelos           NaN  azul         588.0
5    Monterrey           NaN  rojo         675.0
6     Tlaxcala           NaN  azul        3885.0
7    Chihuahua           NaN  rojo        3831.0
8      Yucatán           NaN  azul         339.0

In [0]:
A.merge(right=B, left_on='city', right_on='city', how='inner')

city  population_x color  population_y
0  Guadalajara          4467  rojo          8914
1  Guadalajara          5931  rojo          8914

In [0]:
# https://datos.gob.mx/busca/dataset/numero-de-jornales-pagados
path = '/Users/jacoboleon/Downloads/Empleo_Temporal_Jornales.csv'
#df = pd.read_csv(filepath_or_buffer=path)
df = pd.read_csv(filepath_or_buffer=path, encoding='latin')
df.head(3)

Clave del Estado Nombre del Estado  Clave del Municipio  \
0                 1    AGUASCALIENTES                    1   
1                 1    AGUASCALIENTES                    1   
2                 1    AGUASCALIENTES                    1   

  Nombre del Municipio  Clave de la Localidad  \
0       AGUASCALIENTES                      1   
1       AGUASCALIENTES                    120   
2       AGUASCALIENTES                    121   

             Nombre de la Localidad  Número de Jornales  
0                    AGUASCALIENTES              118220  
1            BUENAVISTA DE PEÑUELAS                2000  
2  CABECITA 3 MARÍAS (RANCHO NUEVO)                 660

In [0]:
df.columns = ['cve_est', 'nom_est', 'cve_mun', 'nom_mun', 'cve_loc', 'nom_loc', 'num_jor']
df.tail(3)

cve_est    nom_est  cve_mun    nom_mun  cve_loc  \
4750       32  ZACATECAS       38      PINOS      534   
4751       32  ZACATECAS       38      PINOS      572   
4752       32  ZACATECAS       56  ZACATECAS        1   

                                       nom_loc  num_jor  
4750                        ESQUINA DE DOLORES      260  
4751  SANTA FE DEL POLVO (VEINTE DE NOVIEMBRE)      360  
4752                                 ZACATECAS    15000

In [0]:
df.nom_est.nunique()

35

In [0]:
df.nom_est.unique()

array(['AGUASCALIENTES', 'BAJA CALIFORNIA', 'BAJA CALIFORNIA SUR',
       'CAMPECHE', 'COAHUILA', 'COAHUILA DE ZARAGOZA', 'COLIMA', 'CHIAPAS',
       'CHIHUAHUA', 'DURANGO', 'GUANAJUATO', 'GUERRERO', 'HIDALGO',
       'JALISCO', 'MEXICO', 'MÉXICO', 'MICHOACAN', 'MICHOACAN DE OCAMPO',
       'MORELOS', 'NAYARIT', 'NUEVO LEON', 'OAXACA', 'PUEBLA', 'QUERETARO',
       'QUINTANA ROO', 'SAN LUIS POTOSI', 'SINALOA', 'SONORA', 'TABASCO',
       'TAMAULIPAS', 'TLAXCALA', 'VERACRUZ DE IGNACIO DE LA LLAVE',
       'VERACRUZ', 'YUCATAN', 'ZACATECAS'], dtype=object)

In [0]:
df.nom_est.value_counts()

MICHOACAN                          706
OAXACA                             655
CHIAPAS                            546
SINALOA                            533
TABASCO                            210
GUERRERO                           196
ZACATECAS                          181
PUEBLA                             165
VERACRUZ DE IGNACIO DE LA LLAVE    164
GUANAJUATO                         151
MEXICO                             137
QUERETARO                          123
YUCATAN                            105
AGUASCALIENTES                     103
NUEVO LEON                          97
NAYARIT                             97
COLIMA                              84
HIDALGO                             81
SAN LUIS POTOSI                     79
QUINTANA ROO                        65
BAJA CALIFORNIA                     38
CHIHUAHUA                           35
TLAXCALA                            34
JALISCO                             33
CAMPECHE                            27
MORELOS                  

In [0]:
pd.pivot_table(df,index=['nom_est'])

cve_est     cve_loc     cve_mun       num_jor
nom_est                                                                       
AGUASCALIENTES                       1.0  294.689320    3.902913   2766.601942
BAJA CALIFORNIA                      2.0  928.736842    2.710526   4356.315789
BAJA CALIFORNIA SUR                  3.0  197.833333    2.166667   3161.111111
CAMPECHE                             4.0  321.148148    6.888889   2232.814815
CHIAPAS                              7.0  182.023810   67.968864   8645.915751
CHIHUAHUA                            8.0    4.000000   29.885714  11343.428571
COAHUILA                             5.0   22.600000   23.400000  30686.000000
COAHUILA DE ZARAGOZA                 5.0    1.000000   18.000000   2400.000000
COLIMA                               6.0   63.333333    5.607143   1471.904762
DURANGO                             10.0   58.937500   24.812500  21951.500000
GUANAJUATO                          11.0  120.006623   21.443709   3437.483444
GUERRERO                            12.0   43.367347   38.673469   6086.295918
HIDALGO                             13.0   17.592593   40.320988   2400.839506
JALISCO                             14.0    1.212121   67.272727  12601.818182
MEXICO                              15.0   48.547445   63.416058  17926.014599
MICHOACAN                           16.0   39.198300   62.531161    964.447592
MICHOACAN DE OCAMPO                 16.0    8.000000   27.000000   1728.000000
MORELOS                             17.0   15.200000   15.760000  21781.600000
MÉXICO                              15.0   33.750000   57.750000  15747.500000
NAYARIT                             18.0   42.567010   11.567010   1332.164948
NUEVO LEON                          19.0   98.494845   22.536082   4220.453608
OAXACA                              20.0   31.787786  253.363359   3635.280916
PUEBLA                              21.0   26.648485  111.503030  10474.012121
QUERETARO                           22.0   56.772358   10.048780   2021.292683
QUINTANA ROO                        23.0  121.369231    5.769231   4718.353846
SAN LUIS POTOSI                     24.0   29.683544   30.556962   2980.202532
SINALOA                             25.0  429.517824    9.757974    857.448405
SONORA                              26.0    1.636364   29.000000  37016.727273
TABASCO                             27.0   82.742857    9.252381   3003.142857
TAMAULIPAS                          28.0  164.789474   24.842105  25133.473684
TLAXCALA                            29.0    7.441176   24.970588   3884.411765
VERACRUZ                            30.0    1.000000  149.666667  46913.333333
VERACRUZ DE IGNACIO DE LA LLAVE     30.0   35.018293   81.920732   2852.981707
YUCATAN                             31.0   53.923810   53.704762   3838.380952
ZACATECAS                           32.0  168.767956   21.044199   1077.569061

In [0]:
pd.pivot_table(df,index=['nom_est', 'nom_mun'])

cve_est      cve_loc  cve_mun  \
nom_est             nom_mun                                                    
AGUASCALIENTES      AGUASCALIENTES                 1.0   585.125000      1.0   
                    ASIENTOS                       1.0    31.000000      2.0   
                    CALVILLO                       1.0    69.000000      3.0   
                    COSÍO                          1.0    14.500000      4.0   
                    EL LLANO                       1.0    78.600000     10.0   
                    JESÚS MARÍA                    1.0    73.250000      5.0   
                    PABELLÓN DE ARTEAGA            1.0    40.833333      6.0   
                    RINCÓN DE ROMOS                1.0    21.333333      7.0   
                    SAN FRANCISCO DE LOS ROMO      1.0    17.333333     11.0   
                    SAN JOSÉ DE GRACIA             1.0    21.000000      8.0   
                    TEPEZALÁ                       1.0    22.500000      9.0   
BAJA CALIFORNIA     ENSENADA                       2.0   507.857143      1.0   
                    MEXICALI                       2.0   698.300000      2.0   
                    TECATE                         2.0  1031.375000      3.0   
                    TIJUANA                        2.0  1269.461538      4.0   
BAJA CALIFORNIA SUR COMONDÚ                        3.0   202.375000      1.0   
                    LA PAZ                         3.0   286.500000      3.0   
                    LORETO                         3.0     1.000000      9.0   
                    MULEGÉ                         3.0   159.000000      2.0   
CAMPECHE            CALAKMUL                       4.0   112.500000     10.0   
                    CALKINI                        4.0    12.000000      1.0   
                    CAMPECHE                       4.0    81.000000      2.0   
                    CANDELARIA                     4.0   285.666667     11.0   
                    CARMEN                         4.0  1689.000000      3.0   
                    CHAMPOTON                      4.0   225.500000      4.0   
                    HECELCHAKAN                    4.0     9.000000      5.0   
                    HOPELCHEN                      4.0   316.000000      6.0   
                    PALIZADA                       4.0   283.272727      7.0   
                    TENABO                         4.0     1.000000      8.0   
CHIAPAS             ACACOYAGUA                     7.0    11.000000      1.0   
...                                                ...          ...      ...   
YUCATAN             SACALUM                       31.0     1.000000     62.0   
                    SAMAHIL                       31.0     1.000000     63.0   
                    SANAHCAT                      31.0     1.000000     64.0   
                    SEYÉ                          31.0     1.000000     67.0   
                    SINANCHÉ                      31.0     2.000000     68.0   
                    SUMA                          31.0     1.000000     72.0   
                    TECOH                         31.0     1.000000     76.0   
                    TEKAL DE VENEGAS              31.0     1.000000     77.0   
                    TEKAX                         31.0     1.000000     79.0   
                    TEKIT                         31.0     1.000000     80.0   
                    TELCHAC PUERTO                31.0     1.000000     83.0   
                    TEMAX                         31.0     1.000000     84.0   
                    TEMOZÓN                       31.0     1.000000     85.0   
                    TICUL                         31.0     1.000000     89.0   
                    TINUM                         31.0     1.000000     91.0   
                    TIXKOKOB                      31.0     1.000000     93.0   
                    TIZIMÍN                       31.0     1.000000     96.0   
                    TUNKÁS                     

In [0]:
pd.pivot_table(df,index=['nom_est', 'nom_mun'], values=['num_jor'])

num_jor
nom_est             nom_mun                                
AGUASCALIENTES      AGUASCALIENTES              4033.750000
                    ASIENTOS                    1702.857143
                    CALVILLO                    1864.000000
                    COSÍO                       1100.000000
                    EL LLANO                     840.000000
                    JESÚS MARÍA                 2357.500000
                    PABELLÓN DE ARTEAGA         2046.666667
                    RINCÓN DE ROMOS             2051.111111
                    SAN FRANCISCO DE LOS ROMO   1116.666667
                    SAN JOSÉ DE GRACIA          1000.000000
                    TEPEZALÁ                    1066.666667
BAJA CALIFORNIA     ENSENADA                    3360.000000
                    MEXICALI                    4974.000000
                    TECATE                      2070.000000
                    TIJUANA                     5824.615385
BAJA CALIFORNIA SUR COMONDÚ                     2120.000000
                    LA PAZ                      6020.000000
                    LORETO                      6840.000000
                    MULEGÉ                      1804.000000
CAMPECHE            CALAKMUL                    1553.000000
                    CALKINI                     1553.000000
                    CAMPECHE                    1553.000000
                    CANDELARIA                  1553.000000
                    CARMEN                       480.000000
                    CHAMPOTON                   1553.000000
                    HECELCHAKAN                 1553.000000
                    HOPELCHEN                   1553.000000
                    PALIZADA                    3494.363636
                    TENABO                       699.000000
CHIAPAS             ACACOYAGUA                  3924.000000
...                                                     ...
YUCATAN             SACALUM                      680.000000
                    SAMAHIL                     3660.000000
                    SANAHCAT                    1000.000000
                    SEYÉ                        3920.000000
                    SINANCHÉ                    2650.000000
                    SUMA                        2960.000000
                    TECOH                       1980.000000
                    TEKAL DE VENEGAS            5544.000000
                    TEKAX                       9400.000000
                    TEKIT                       3740.000000
                    TELCHAC PUERTO              1000.000000
                    TEMAX                       2960.000000
                    TEMOZÓN                     2880.000000
                    TICUL                      69940.000000
                    TINUM                       3780.000000
                    TIXKOKOB                    5160.000000
                    TIZIMÍN                    11560.000000
                    TUNKÁS                      3900.000000
                    TZUCACAB                    3000.000000
                    UCÚ                         3980.000000
                    UMÁN                        7020.000000
                    VALLADOLID                  2860.000000
                    XOCCHEL                     2600.000000
                    YAXCABÁ                     9740.000000
                    YAXKUKUL                    3760.000000
                    YOBAÍN                      3180.000000
ZACATECAS           FRESNILLO                    913.939394
                    GUADALUPE                   3469.333333
                    PINOS                        568.484848
                    ZACATECAS                  15000.000000

[946 rows x 1 columns]

In [0]:
pd.pivot_table(df,index=['nom_est', 'nom_mun'], values=['num_jor'], aggfunc=np.sum)

num_jor
nom_est             nom_mun                           
AGUASCALIENTES      AGUASCALIENTES              193620
                    ASIENTOS                     11920
                    CALVILLO                      9320
                    COSÍO                         2200
                    EL LLANO                      4200
                    JESÚS MARÍA                  18860
                    PABELLÓN DE ARTEAGA          12280
                    RINCÓN DE ROMOS              18460
                    SAN FRANCISCO DE LOS ROMO     6700
                    SAN JOSÉ DE GRACIA            1000
                    TEPEZALÁ                      6400
BAJA CALIFORNIA     ENSENADA                     23520
                    MEXICALI                     49740
                    TECATE                       16560
                    TIJUANA                      75720
BAJA CALIFORNIA SUR COMONDÚ                      16960
                    LA PAZ                       24080
                    LORETO                        6840
                    MULEGÉ                        9020
CAMPECHE            CALAKMUL                      6212
                    CALKINI                       1553
                    CAMPECHE                      1553
                    CANDELARIA                    4659
                    CARMEN                         960
                    CHAMPOTON                     3106
                    HECELCHAKAN                   1553
                    HOPELCHEN                     1553
                    PALIZADA                     38438
                    TENABO                         699
CHIAPAS             ACACOYAGUA                    7848
...                                                ...
YUCATAN             SACALUM                        680
                    SAMAHIL                       3660
                    SANAHCAT                      1000
                    SEYÉ                          3920
                    SINANCHÉ                      5300
                    SUMA                          2960
                    TECOH                         1980
                    TEKAL DE VENEGAS              5544
                    TEKAX                         9400
                    TEKIT                         3740
                    TELCHAC PUERTO                1000
                    TEMAX                         2960
                    TEMOZÓN                       2880
                    TICUL                        69940
                    TINUM                         3780
                    TIXKOKOB                      5160
                    TIZIMÍN                      11560
                    TUNKÁS                        3900
                    TZUCACAB                      3000
                    UCÚ                           3980
                    UMÁN                          7020
                    VALLADOLID                    2860
                    XOCCHEL                       2600
                    YAXCABÁ                       9740
                    YAXKUKUL                      3760
                    YOBAÍN                        3180
ZACATECAS           FRESNILLO                    90480
                    GUADALUPE                    52040
                    PINOS                        37520
                    ZACATECAS                    15000

[946 rows x 1 columns]

In [0]:
pd.pivot_table(df,index=['nom_est', 'nom_mun'], values=['num_jor'], aggfunc=[np.mean,np.median])

mean   median
                                                    num_jor  num_jor
nom_est             nom_mun                                         
AGUASCALIENTES      AGUASCALIENTES              4033.750000   1000.0
                    ASIENTOS                    1702.857143   1000.0
                    CALVILLO                    1864.000000   1940.0
                    COSÍO                       1100.000000   1100.0
                    EL LLANO                     840.000000    600.0
                    JESÚS MARÍA                 2357.500000   1090.0
                    PABELLÓN DE ARTEAGA         2046.666667   2000.0
                    RINCÓN DE ROMOS             2051.111111   1400.0
                    SAN FRANCISCO DE LOS ROMO   1116.666667   1100.0
                    SAN JOSÉ DE GRACIA          1000.000000   1000.0
                    TEPEZALÁ                    1066.666667   1000.0
BAJA CALIFORNIA     ENSENADA                    3360.000000    980.0
                    MEXICALI                    4974.000000   2380.0
                    TECATE                      2070.000000   2290.0
                    TIJUANA                     5824.615385   1800.0
BAJA CALIFORNIA SUR COMONDÚ                     2120.000000   1040.0
                    LA PAZ                      6020.000000   5160.0
                    LORETO                      6840.000000   6840.0
                    MULEGÉ                      1804.000000   1420.0
CAMPECHE            CALAKMUL                    1553.000000   1553.0
                    CALKINI                     1553.000000   1553.0
                    CAMPECHE                    1553.000000   1553.0
                    CANDELARIA                  1553.000000   1553.0
                    CARMEN                       480.000000    480.0
                    CHAMPOTON                   1553.000000   1553.0
                    HECELCHAKAN                 1553.000000   1553.0
                    HOPELCHEN                   1553.000000   1553.0
                    PALIZADA                    3494.363636   2691.0
                    TENABO                       699.000000    699.0
CHIAPAS             ACACOYAGUA                  3924.000000   3924.0
...                                                     ...      ...
YUCATAN             SACALUM                      680.000000    680.0
                    SAMAHIL                     3660.000000   3660.0
                    SANAHCAT                    1000.000000   1000.0
                    SEYÉ                        3920.000000   3920.0
                    SINANCHÉ                    2650.000000   2650.0
                    SUMA                        2960.000000   2960.0
                    TECOH                       1980.000000   1980.0
                    TEKAL DE VENEGAS            5544.000000   5544.0
                    TEKAX                       9400.000000   9400.0
                    TEKIT                       3740.000000   3740.0
                    TELCHAC PUERTO              1000.000000   1000.0
                    TEMAX                       2960.000000   2960.0
                    TEMOZÓN                     2880.000000   2880.0
                    TICUL                      69940.000000  69940.0
                    TINUM                       3780.000000   3780.0
                    TIXKOKOB                    5160.000000   5160.0
                    TIZIMÍN                    11560.000000  11560.0
                    TUNKÁS                      3900.000000   3900.0
                    TZUCACAB                    3000.000000   3000.0
                    UCÚ                         3980.000000   3980.0
                    UMÁN                        7020.000000   7020.0
                    VALLADOLID                  2860.000000   2860.0
                    XOCCHEL                     2600.000000   2600.0
                    YAXCABÁ                     9740.000000   9740.0
                    YAXKUKUL                    3760.

In [0]:
pd.pivot_table(df,index=['nom_est'], columns=['nom_mun'], values=['num_jor'])

num_jor                                  \
nom_mun                           ABALÁ ACACOYAGUA        ACALA ACAMBAY   
nom_est                                                                   
AGUASCALIENTES                      NaN        NaN          NaN     NaN   
BAJA CALIFORNIA                     NaN        NaN          NaN     NaN   
BAJA CALIFORNIA SUR                 NaN        NaN          NaN     NaN   
CAMPECHE                            NaN        NaN          NaN     NaN   
CHIAPAS                             NaN     3924.0  3293.333333     NaN   
CHIHUAHUA                           NaN        NaN          NaN     NaN   
COAHUILA                            NaN        NaN          NaN     NaN   
COAHUILA DE ZARAGOZA                NaN        NaN          NaN     NaN   
COLIMA                              NaN        NaN          NaN     NaN   
DURANGO                             NaN        NaN          NaN     NaN   
GUANAJUATO                          NaN        NaN          NaN     NaN   
GUERRERO                            NaN        NaN          NaN     NaN   
HIDALGO                             NaN        NaN          NaN     NaN   
JALISCO                             NaN        NaN          NaN     NaN   
MEXICO                              NaN        NaN          NaN  3780.0   
MICHOACAN                           NaN        NaN          NaN     NaN   
MICHOACAN DE OCAMPO                 NaN        NaN          NaN     NaN   
MORELOS                             NaN        NaN          NaN     NaN   
MÉXICO                              NaN        NaN          NaN     NaN   
NAYARIT                             NaN        NaN          NaN     NaN   
NUEVO LEON                          NaN        NaN          NaN     NaN   
OAXACA                              NaN        NaN          NaN     NaN   
PUEBLA                              NaN        NaN          NaN     NaN   
QUERETARO                           NaN        NaN          NaN     NaN   
QUINTANA ROO                        NaN        NaN          NaN     NaN   
SAN LUIS POTOSI                     NaN        NaN          NaN     NaN   
SINALOA                             NaN        NaN          NaN     NaN   
SONORA                              NaN        NaN          NaN     NaN   
TABASCO                             NaN        NaN          NaN     NaN   
TAMAULIPAS                          NaN        NaN          NaN     NaN   
TLAXCALA                            NaN        NaN          NaN     NaN   
VERACRUZ                            NaN        NaN          NaN     NaN   
VERACRUZ DE IGNACIO DE LA LLAVE     NaN        NaN          NaN     NaN   
YUCATAN                          2960.0        NaN          NaN     NaN   
ZACATECAS                           NaN        NaN          NaN     NaN   

                                                              \
nom_mun                         ACANCEH ACAPETAHUA ACAPONETA   
nom_est                                                        
AGUASCALIENTES                      NaN        NaN       NaN   
BAJA CALIFORNIA                     NaN        NaN       NaN   
BAJA CALIFORNIA SUR                 NaN        NaN       NaN   
CAMPECHE                            NaN        NaN       NaN   
CHIAPAS                             NaN    12196.0       NaN   
CHIHUAHUA                           NaN        NaN       NaN   
COAHUILA                            NaN        NaN       NaN   
COAHUILA DE ZARAGOZA                NaN        NaN       NaN   
COLIMA                              NaN        NaN       NaN   
DURANGO                             NaN        NaN       NaN   
GUANAJUATO                          NaN        NaN       NaN   
GUERRERO                            NaN        NaN       NaN   
HIDALGO                             NaN        NaN       NaN   
JALISCO                             NaN        NaN       NaN   
MEXICO                              NaN        NaN       NaN   
MICHOACAN                    

In [0]:
pd.pivot_table(df,index=['nom_est'], columns=['nom_mun'], values=['num_jor'], dropna=True)

num_jor                                  \
nom_mun                           ABALÁ ACACOYAGUA        ACALA ACAMBAY   
nom_est                                                                   
AGUASCALIENTES                      NaN        NaN          NaN     NaN   
BAJA CALIFORNIA                     NaN        NaN          NaN     NaN   
BAJA CALIFORNIA SUR                 NaN        NaN          NaN     NaN   
CAMPECHE                            NaN        NaN          NaN     NaN   
CHIAPAS                             NaN     3924.0  3293.333333     NaN   
CHIHUAHUA                           NaN        NaN          NaN     NaN   
COAHUILA                            NaN        NaN          NaN     NaN   
COAHUILA DE ZARAGOZA                NaN        NaN          NaN     NaN   
COLIMA                              NaN        NaN          NaN     NaN   
DURANGO                             NaN        NaN          NaN     NaN   
GUANAJUATO                          NaN        NaN          NaN     NaN   
GUERRERO                            NaN        NaN          NaN     NaN   
HIDALGO                             NaN        NaN          NaN     NaN   
JALISCO                             NaN        NaN          NaN     NaN   
MEXICO                              NaN        NaN          NaN  3780.0   
MICHOACAN                           NaN        NaN          NaN     NaN   
MICHOACAN DE OCAMPO                 NaN        NaN          NaN     NaN   
MORELOS                             NaN        NaN          NaN     NaN   
MÉXICO                              NaN        NaN          NaN     NaN   
NAYARIT                             NaN        NaN          NaN     NaN   
NUEVO LEON                          NaN        NaN          NaN     NaN   
OAXACA                              NaN        NaN          NaN     NaN   
PUEBLA                              NaN        NaN          NaN     NaN   
QUERETARO                           NaN        NaN          NaN     NaN   
QUINTANA ROO                        NaN        NaN          NaN     NaN   
SAN LUIS POTOSI                     NaN        NaN          NaN     NaN   
SINALOA                             NaN        NaN          NaN     NaN   
SONORA                              NaN        NaN          NaN     NaN   
TABASCO                             NaN        NaN          NaN     NaN   
TAMAULIPAS                          NaN        NaN          NaN     NaN   
TLAXCALA                            NaN        NaN          NaN     NaN   
VERACRUZ                            NaN        NaN          NaN     NaN   
VERACRUZ DE IGNACIO DE LA LLAVE     NaN        NaN          NaN     NaN   
YUCATAN                          2960.0        NaN          NaN     NaN   
ZACATECAS                           NaN        NaN          NaN     NaN   

                                                              \
nom_mun                         ACANCEH ACAPETAHUA ACAPONETA   
nom_est                                                        
AGUASCALIENTES                      NaN        NaN       NaN   
BAJA CALIFORNIA                     NaN        NaN       NaN   
BAJA CALIFORNIA SUR                 NaN        NaN       NaN   
CAMPECHE                            NaN        NaN       NaN   
CHIAPAS                             NaN    12196.0       NaN   
CHIHUAHUA                           NaN        NaN       NaN   
COAHUILA                            NaN        NaN       NaN   
COAHUILA DE ZARAGOZA                NaN        NaN       NaN   
COLIMA                              NaN        NaN       NaN   
DURANGO                             NaN        NaN       NaN   
GUANAJUATO                          NaN        NaN       NaN   
GUERRERO                            NaN        NaN       NaN   
HIDALGO                             NaN        NaN       NaN   
JALISCO                             NaN        NaN       NaN   
MEXICO                              NaN        NaN       NaN   
MICHOACAN                    

In [0]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
# use Seaborn styles
sns.set()  

pd.pivot_table(df,index=['nom_est'], columns=['nom_mun'], values=['num_jor']).plot(kind= 'bar')
plt.ylabel("Happiness Rank")